conclusion: fix tests

diff --git a/.github/workflows/test-conclusion-failure.yml b/.github/workflows/test-conclusion-failure.yml
--- a/.github/workflows/test-conclusion-failure.yml
+++ b/.github/workflows/test-conclusion-failure.yml
@@ -26,4 +26,6 @@ jobs:
         id: conclusion
       - name: assert conclusion
         if: steps.conclusion.outputs.conclusion != 'failure'
-        run: echo "::error::Conclusion mismatch (expected:\ failure, got:\ ${{ steps.conclusion.outputs.conclusion }})"
+        run: |
+          echo "::error::Conclusion mismatch (expected: failure, got: ${{ steps.conclusion.outputs.conclusion }})"
+          exit 1
diff --git a/.github/workflows/test-conclusion-success.yml b/.github/workflows/test-conclusion-success.yml
--- a/.github/workflows/test-conclusion-success.yml
+++ b/.github/workflows/test-conclusion-success.yml
@@ -24,4 +24,6 @@ jobs:
         id: conclusion
       - name: assert conclusion
         if: steps.conclusion.outputs.conclusion != 'success'
-        run: echo "::error::Conclusion mismatch (expected:\ success, got:\ ${{ steps.conclusion.outputs.conclusion }})"
+        run: |
+          echo "::error::Conclusion mismatch (expected: success, got: ${{ steps.conclusion.outputs.conclusion }})"
+          exit 1
